export const Colleges = [
    {
        "ranking": "3",
        "name": "IIT Bombay - Indian Institute of Technology Bombay",
        "city": "Mumbai",
        "state": "Maharashtra",
        "course": "B.Tech in Computer Science",
        "course_fee": "900000",
        "average_package": "2000000",
        "highest_package": "3400000",
        "collegeduniya_rating": "9.5",
        "user_rating": "9.2",
        "featured": true
    },
    {
        "ranking": "2",
        "name": "IIT Delhi - Indian Institute of Technology Delhi",
        "city": "New Delhi",
        "state": "Delhi",
        "course": "B.Tech in Electrical Engineering",
        "course_fee": "880000",
        "average_package": "1900000",
        "highest_package": "3300000",
        "collegeduniya_rating": "9.3",
        "user_rating": "9.0",
        "featured": true
    },
    {
        "ranking": "1",
        "name": "IIT Madras - Indian Institute of Technology Madras",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "course": "B.Tech in Mechanical Engineering",
        "course_fee": "800000",
        "average_package": "1800000",
        "highest_package": "3200000",
        "collegeduniya_rating": "9.4",
        "user_rating": "9.1",
        "featured": true
    },
    {
        "ranking": "4",
        "name": "IIT Kanpur - Indian Institute of Technology Kanpur",
        "city": "Kanpur",
        "state": "Uttar Pradesh",
        "course": "B.Tech in Aerospace Engineering",
        "course_fee": "850000",
        "average_package": "1700000",
        "highest_package": "3100000",
        "collegeduniya_rating": "9.0",
        "user_rating": "8.8",
        "featured": false
    },
    {
        "ranking": "6",
        "name": "IIT Kharagpur - Indian Institute of Technology Kharagpur",
        "city": "Kharagpur",
        "state": "West Bengal",
        "course": "B.Tech in Civil Engineering",
        "course_fee": "820000",
        "average_package": "1600000",
        "highest_package": "3000000",
        "collegeduniya_rating": "9.2",
        "user_rating": "9.0",
        "featured": false
    },
    {
        "ranking": "5",
        "name": "IIT Roorkee - Indian Institute of Technology Roorkee",
        "city": "Roorkee",
        "state": "Uttarakhand",
        "course": "B.Tech in Chemical Engineering",
        "course_fee": "860000",
        "average_package": "1500000",
        "highest_package": "2900000",
        "collegeduniya_rating": "8.9",
        "user_rating": "8.7",
        "featured": false
    },
    {
        "ranking": "7",
        "name": "IIT Guwahati - Indian Institute of Technology Guwahati",
        "city": "Guwahati",
        "state": "Assam",
        "course": "B.Tech in Electronics and Communication Engineering",
        "course_fee": "870000",
        "average_package": "1700000",
        "highest_package": "3050000",
        "collegeduniya_rating": "8.8",
        "user_rating": "8.6",
        "featured": false
    },
    {
        "ranking": "8",
        "name": "IIT Hyderabad - Indian Institute of Technology Hyderabad",
        "city": "Hyderabad",
        "state": "Telangana",
        "course": "B.Tech in Artificial Intelligence",
        "course_fee": "900000",
        "average_package": "1800000",
        "highest_package": "3500000",
        "collegeduniya_rating": "9.1",
        "user_rating": "9.0",
        "featured": true
    },
    {
        "ranking": "15",
        "name": "IIT BHU - Indian Institute of Technology (BHU) Varanasi",
        "city": "Varanasi",
        "state": "Uttar Pradesh",
        "course": "B.Tech in Metallurgical Engineering",
        "course_fee": "864000",
        "average_package": "1580000",
        "highest_package": "3075000",
        "collegeduniya_rating": "8.7",
        "user_rating": "8.5",
        "featured": false
    },
    {
        "ranking": "14",
        "name": "IIT Indore - Indian Institute of Technology Indore",
        "city": "Indore",
        "state": "Madhya Pradesh",
        "course": "B.Tech in Civil Engineering",
        "course_fee": "830000",
        "average_package": "1470000",
        "highest_package": "2920000",
        "collegeduniya_rating": "8.4",
        "user_rating": "8.2",

        "featured": false
    },
    {
        "ranking": "17",
        "name": "IIT Dhanbad - Indian Institute of Technology (ISM) Dhanbad",
        "city": "Dhanbad",
        "state": "Jharkhand",
        "course": "B.Tech in Petroleum Engineering",
        "course_fee": "876000",
        "average_package": "1650000",
        "highest_package": "3100000",
        "collegeduniya_rating": "8.6",
        "user_rating": "8.4",

        "featured": false
    },
    {
        "ranking": "44",
        "name": "IIT Bhubaneswar - Indian Institute of Technology Bhubaneswar",
        "city": "Bhubaneswar",
        "state": "Odisha",
        "course": "B.Tech in Ocean Engineering and Naval Architecture",
        "course_fee": "850000",
        "average_package": "1400000",
        "highest_package": "2850000",
        "collegeduniya_rating": "8.2",
        "user_rating": "8.0",

        "featured": false
    },
    {
        "ranking": "18",
        "name": "IIT Gandhinagar - Indian Institute of Technology Gandhinagar",
        "city": "Gandhinagar",
        "state": "Gujarat",
        "course": "B.Tech in Chemical Engineering",
        "course_fee": "860000",
        "average_package": "1500000",
        "highest_package": "3000000",
        "collegeduniya_rating": "8.5",
        "user_rating": "8.3",

        "featured": false
    },
    {
        "ranking": "22",
        "name": "IIT Ropar - Indian Institute of Technology Ropar",
        "city": "Ropar",
        "state": "Punjab",
        "course": "B.Tech in Mechanical Engineering",
        "course_fee": "845000",
        "average_package": "1600000",
        "highest_package": "2950000",
        "collegeduniya_rating": "8.1",
        "user_rating": "7.9",

        "featured": false
    },
    {
        "ranking": "41",
        "name": "IIT Patna - Indian Institute of Technology Patna",
        "city": "Patna",
        "state": "Bihar",
        "course": "B.Tech in Electrical Engineering",
        "course_fee": "832000",
        "average_package": "1550000",
        "highest_package": "3050000",
        "collegeduniya_rating": "8.3",
        "user_rating": "8.1",

        "featured": false
    },
    {
        "ranking": "33",
        "name": "IIT Mandi - Indian Institute of Technology Mandi",
        "city": "Mandi",
        "state": "Himachal Pradesh",
        "course": "B.Tech in Data Science and Engineering",
        "course_fee": "878000",
        "average_package": "1450000",
        "highest_package": "3200000",
        "collegeduniya_rating": "8.0",
        "user_rating": "7.8",

        "featured": false
    },
    {
        "ranking": "30",
        "name": "IIT Jodhpur - Indian Institute of Technology Jodhpur",
        "city": "Jodhpur",
        "state": "Rajasthan",
        "course": "B.Tech in Artificial Intelligence and Data Science",
        "course_fee": "900000",
        "average_package": "1600000",
        "highest_package": "3250000",
        "collegeduniya_rating": "8.4",
        "user_rating": "8.2",

        "featured": false
    },
    {
        "ranking": "59",
        "name": "IIT Tirupati - Indian Institute of Technology Tirupati",
        "city": "Tirupati",
        "state": "Andhra Pradesh",
        "course": "B.Tech in Civil Engineering",
        "course_fee": "820000",
        "average_package": "1350000",
        "highest_package": "2800000",
        "collegeduniya_rating": "7.9",
        "user_rating": "7.7",

        "featured": false
    },
    {
        "ranking": "69",
        "name": "IIT Palakkad - Indian Institute of Technology Palakkad",
        "city": "Palakkad",
        "state": "Kerala",
        "course": "B.Tech in Mechanical Engineering",
        "course_fee": "855000",
        "average_package": "1450000",
        "highest_package": "2900000",
        "collegeduniya_rating": "7.8",
        "user_rating": "7.6",

        "featured": false
    },
    {
        "ranking": "21",
        "name": "IIT Goa - Indian Institute of Technology Goa",
        "city": "Goa",
        "state": "Goa",
        "course": "B.Tech in Computer Science and Engineering",
        "course_fee": "880000",
        "average_package": "1500000",
        "highest_package": "3100000",
        "collegeduniya_rating": "7.7",
        "user_rating": "7.5",

        "featured": false
    },
    {
        "ranking": "93",
        "name": "IIT Dharwad - Indian Institute of Technology Dharwad",
        "city": "Dharwad",
        "state": "Karnataka",
        "course": "B.Tech in Electrical Engineering",
        "course_fee": "825000",
        "average_package": "1400000",
        "highest_package": "2950000",
        "collegeduniya_rating": "7.6",
        "user_rating": "7.4",

        "featured": false
    },
    {
        "ranking": "81",
        "name": "IIT Bhilai - Indian Institute of Technology Bhilai",
        "city": "Bhilai",
        "state": "Chhattisgarh",
        "course": "B.Tech in Mechanical Engineering",
        "course_fee": "840000",
        "average_package": "1380000",
        "highest_package": "2850000",
        "collegeduniya_rating": "7.5",
        "user_rating": "7.3",

        "featured": false
    },
    {
        "ranking": "67",
        "name": "IIT Jammu - Indian Institute of Technology Jammu",
        "city": "Jammu",
        "state": "Jammu and Kashmir",
        "course": "B.Tech in Computer Science and Engineering",
        "course_fee": "850000",
        "average_package": "1420000",
        "highest_package": "3000000",
        "collegeduniya_rating": "7.4",
        "user_rating": "7.2",

        "featured": false
    },
    {
        "ranking": "9",
        "name": "NIT Trichy - National Institute of Technology, Tiruchirappalli",
        "city": "Tiruchirappalli",
        "state": "Tamil Nadu",
        "course": "B.Tech in Mechanical Engineering",
        "course_fee": "525000",
        "average_package": "1200000",
        "highest_package": "4200000",
        "collegeduniya_rating": "9.2",
        "user_rating": "9.0",
        "featured": true
    },
    {
        "ranking": "12",
        "name": "NIT Surathkal - National Institute of Technology, Surathkal",
        "city": "Mangalore",
        "state": "Karnataka",
        "course": "B.Tech in Computer Engineering",
        "course_fee": "500000",
        "average_package": "1150000",
        "highest_package": "4000000",
        "collegeduniya_rating": "9.0",
        "user_rating": "8.9",
        "featured": true
    },
    {
        "ranking": "20",
        "name": "NIT Warangal - National Institute of Technology, Warangal",
        "city": "Warangal",
        "state": "Telangana",
        "course": "B.Tech in Electrical and Electronics Engineering",
        "course_fee": "530000",
        "average_package": "1100000",
        "highest_package": "3800000",
        "collegeduniya_rating": "8.8",
        "user_rating": "8.7",
        "featured": false
    },
    {
        "ranking": "23",
        "name": "NIT Calicut - National Institute of Technology, Calicut",
        "city": "Kozhikode",
        "state": "Kerala",
        "course": "B.Tech in Civil Engineering",
        "course_fee": "510000",
        "average_package": "950000",
        "highest_package": "3500000",
        "collegeduniya_rating": "8.5",
        "user_rating": "8.4",
        "featured": false
    },
    {
        "ranking": "16",
        "name": "NIT Rourkela - National Institute of Technology, Rourkela",
        "city": "Rourkela",
        "state": "Odisha",
        "course": "B.Tech in Metallurgical and Materials Engineering",
        "course_fee": "540000",
        "average_package": "1000000",
        "highest_package": "3700000",
        "collegeduniya_rating": "8.7",
        "user_rating": "8.5",
        "featured": false
    },
    {
        "ranking": "37",
        "name": "NIT Jaipur - Malaviya National Institute of Technology",
        "city": "Jaipur",
        "state": "Rajasthan",
        "course": "B.Tech in Chemical Engineering",
        "course_fee": "495000",
        "average_package": "900000",
        "highest_package": "3300000",
        "collegeduniya_rating": "8.2",
        "user_rating": "8.1",
        "featured": false
    },
    {
        "ranking": "80",
        "name": "NIT Bhopal - Maulana Azad National Institute of Technology",
        "city": "Bhopal",
        "state": "Madhya Pradesh",
        "course": "B.Tech in Information Technology",
        "course_fee": "515000",
        "average_package": "925000",
        "highest_package": "3400000",
        "collegeduniya_rating": "8.3",
        "user_rating": "8.2",
        "featured": false
    },
    {
        "ranking": "49",
        "name": "NIT Allahabad - Motilal Nehru National Institute of Technology",
        "city": "Allahabad",
        "state": "Uttar Pradesh",
        "course": "B.Tech in Electronics and Communication Engineering",
        "course_fee": "520000",
        "average_package": "980000",
        "highest_package": "3600000",
        "collegeduniya_rating": "8.6",
        "user_rating": "8.4",
        "featured": false
    },
    {
        "ranking": "43",
        "name": "NIT Durgapur - National Institute of Technology, Durgapur",
        "city": "Durgapur",
        "state": "West Bengal",
        "course": "B.Tech in Mechanical Engineering",
        "course_fee": "505000",
        "average_package": "890000",
        "highest_package": "3200000",
        "collegeduniya_rating": "8.0",
        "user_rating": "7.9",
        "featured": false
    },
    {
        "ranking": "40",
        "name": "NIT Silchar - National Institute of Technology, Silchar",
        "city": "Silchar",
        "state": "Assam",
        "course": "B.Tech in Computer Science and Engineering",
        "course_fee": "510000",
        "average_package": "920000",
        "highest_package": "3300000",
        "collegeduniya_rating": "8.1",
        "user_rating": "8.0",

        "featured": false
    },
    {
        "ranking": "50",
        "name": "NIT Hamirpur - National Institute of Technology, Hamirpur",
        "city": "Hamirpur",
        "state": "Himachal Pradesh",
        "course": "B.Tech in Electrical Engineering",
        "course_fee": "525000",
        "average_package": "950000",
        "highest_package": "3400000",
        "collegeduniya_rating": "8.0",
        "user_rating": "7.9",

        "featured": false
    },
    {
        "ranking": "46",
        "name": "NIT Jalandhar - Dr. B. R. Ambedkar National Institute of Technology",
        "city": "Jalandhar",
        "state": "Punjab",
        "course": "B.Tech in Civil Engineering",
        "course_fee": "515000",
        "average_package": "900000",
        "highest_package": "3100000",
        "collegeduniya_rating": "7.9",
        "user_rating": "7.8",

        "featured": false
    },
    {
        "ranking": "91",
        "name": "NIT Agartala - National Institute of Technology, Agartala",
        "city": "Agartala",
        "state": "Tripura",
        "course": "B.Tech in Electronics and Instrumentation Engineering",
        "course_fee": "505000",
        "average_package": "870000",
        "highest_package": "3000000",
        "collegeduniya_rating": "7.8",
        "user_rating": "7.7",

        "featured": false
    },
    {
        "ranking": "58",
        "name": "NIT Kurukshetra - National Institute of Technology, Kurukshetra",
        "city": "Kurukshetra",
        "state": "Haryana",
        "course": "B.Tech in Biotechnology",
        "course_fee": "520000",
        "average_package": "925000",
        "highest_package": "3200000",
        "collegeduniya_rating": "7.7",
        "user_rating": "7.6",

        "featured": false
    },
    {
        "ranking": "70",
        "name": "NIT Raipur - National Institute of Technology, Raipur",
        "city": "Raipur",
        "state": "Chhattisgarh",
        "course": "B.Tech in Mining Engineering",
        "course_fee": "515000",
        "average_package": "880000",
        "highest_package": "3000000",
        "collegeduniya_rating": "7.6",
        "user_rating": "7.5",

        "featured": false
    },
    {
        "ranking": "55",
        "name": "IIIT Hyderabad - International Institute of Information Technology, Hyderabad",
        "city": "Hyderabad",
        "state": "Telangana",
        "course": "B.Tech in Computer Science and Engineering",
        "course_fee": "700000",
        "average_package": "1800000",
        "highest_package": "3500000",
        "collegeduniya_rating": "9.5",
        "user_rating": "9.3",
        "featured": true
    },
    {
        "ranking": "74",
        "name": "IIIT Bangalore - International Institute of Information Technology, Bangalore",
        "city": "Bangalore",
        "state": "Karnataka",
        "course": "B.Tech in Information Technology",
        "course_fee": "680000",
        "average_package": "1700000",
        "highest_package": "3300000",
        "collegeduniya_rating": "9.4",
        "user_rating": "9.2",
        "featured": true
    },
    {
        "ranking": "75",
        "name": "IIIT Delhi - Indraprastha Institute of Information Technology, Delhi",
        "city": "New Delhi",
        "state": "Delhi",
        "course": "B.Tech in Computer Science and Applied Mathematics",
        "course_fee": "720000",
        "average_package": "1850000",
        "highest_package": "3600000",
        "collegeduniya_rating": "9.3",
        "user_rating": "9.1",
        "featured": true
    },
    {
        "ranking": "89",
        "name": "IIIT Allahabad - Indian Institute of Information Technology, Allahabad",
        "city": "Allahabad",
        "state": "Uttar Pradesh",
        "course": "B.Tech in Electronics and Communication Engineering",
        "course_fee": "690000",
        "average_package": "1750000",
        "highest_package": "3400000",
        "collegeduniya_rating": "9.2",
        "user_rating": "9.0",
        "featured": false
    },
    {
        "ranking": "84",
        "name": "IIIT Pune - International Institute of Information Technology, Pune",
        "city": "Pune",
        "state": "Maharashtra",
        "course": "B.Tech in Artificial Intelligence",
        "course_fee": "710000",
        "average_package": "1800000",
        "highest_package": "3500000",
        "collegeduniya_rating": "9.1",
        "user_rating": "8.9",
        "featured": false
    },
    {
        "ranking": "102",
        "name": "IIIT Guwahati - Indian Institute of Information Technology, Guwahati",
        "city": "Guwahati",
        "state": "Assam",
        "course": "B.Tech in Computer Engineering",
        "course_fee": "680000",
        "average_package": "1700000",
        "highest_package": "3300000",
        "collegeduniya_rating": "9.0",
        "user_rating": "8.8",
        "featured": false
    },
    {
        "ranking": "104",
        "name": "IIIT Bhubaneswar - International Institute of Information Technology, Bhubaneswar",
        "city": "Bhubaneswar",
        "state": "Odisha",
        "course": "B.Tech in Information Technology",
        "course_fee": "700000",
        "average_package": "1750000",
        "highest_package": "3400000",
        "collegeduniya_rating": "8.9",
        "user_rating": "8.7",
        "featured": false
    },
    {
        "ranking": "108",
        "name": "IIIT Jabalpur - Indian Institute of Information Technology, Jabalpur",
        "city": "Jabalpur",
        "state": "Madhya Pradesh",
        "course": "B.Tech in Computer Science and Engineering",
        "course_fee": "690000",
        "average_package": "1720000",
        "highest_package": "3350000",
        "collegeduniya_rating": "8.8",
        "user_rating": "8.6",
        "featured": false
    },
    {
        "ranking": "112",
        "name": "IIIT Lucknow - Indian Institute of Information Technology, Lucknow",
        "city": "Lucknow",
        "state": "Uttar Pradesh",
        "course": "B.Tech in Electronics and Communication Engineering",
        "course_fee": "685000",
        "average_package": "1730000",
        "highest_package": "3380000",
        "collegeduniya_rating": "8.7",
        "user_rating": "8.5",
        "featured": false
    },
    {
        "ranking": "117",
        "name": "IIIT Kota - Indian Institute of Information Technology, Kota",
        "city": "Kota",
        "state": "Rajasthan",
        "course": "B.Tech in Information Technology",
        "course_fee": "680000",
        "average_package": "1700000",
        "highest_package": "3300000",
        "collegeduniya_rating": "8.6",
        "user_rating": "8.4",

        "featured": false
    },
    {
        "ranking": "11",
        "name": "BITS Pilani - Birla Institute of Technology and Science",
        "city": "Pilani",
        "state": "Rajasthan",
        "course": "B.Tech in Computer Science and Engineering",
        "course_fee": "1500000",
        "average_package": "1800000",
        "highest_package": "5000000",
        "collegeduniya_rating": "9.5",
        "user_rating": "9.3",
        "featured": true
    },
    {
        "ranking": "25",
        "name": "VIT Vellore - Vellore Institute of Technology",
        "city": "Vellore",
        "state": "Tamil Nadu",
        "course": "B.Tech in Electronics and Communication Engineering",
        "course_fee": "1400000",
        "average_package": "1700000",
        "highest_package": "4800000",
        "collegeduniya_rating": "9.3",
        "user_rating": "9.1",
        "featured": true
    },
    {
        "ranking": "28",
        "name": "SRM Chennai - SRM Institute of Science and Technology",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "course": "B.Tech in Information Technology",
        "course_fee": "1600000",
        "average_package": "1600000",
        "highest_package": "4600000",
        "collegeduniya_rating": "9.1",
        "user_rating": "8.9",
        "featured": true
    },
    {
        "ranking": "76",
        "name": "Manipal Institute of Technology",
        "city": "Manipal",
        "state": "Karnataka",
        "course": "B.Tech in Mechanical Engineering",
        "course_fee": "1550000",
        "average_package": "1500000",
        "highest_package": "4500000",
        "collegeduniya_rating": "8.9",
        "user_rating": "8.7",
        "featured": false
    },
    {
        "ranking": "31",
        "name": "Amity University, Noida",
        "city": "Noida",
        "state": "Uttar Pradesh",
        "course": "B.Tech in Civil Engineering",
        "course_fee": "1450000",
        "average_package": "1400000",
        "highest_package": "4400000",
        "collegeduniya_rating": "8.7",
        "user_rating": "8.5",
        "featured": false
    },
    {
        "ranking": "63",
        "name": "PSG College of Technology, Coimbatore",
        "city": "Coimbatore",
        "state": "Tamil Nadu",
        "course": "B.Tech in Electrical and Electronics Engineering",
        "course_fee": "1350000",
        "average_package": "1300000",
        "highest_package": "4300000",
        "collegeduniya_rating": "8.6",
        "user_rating": "8.4",
        "featured": false
    },
    {
        "ranking": "24",
        "name": "Thapar Institute of Engineering and Technology, Patiala",
        "city": "Patiala",
        "state": "Punjab",
        "course": "B.Tech in Computer Engineering",
        "course_fee": "1500000",
        "average_package": "1600000",
        "highest_package": "4600000",
        "collegeduniya_rating": "8.8",
        "user_rating": "8.6",
        "featured": false
    },
    {
        "ranking": "83",
        "name": "Symbiosis Institute of Technology, Pune",
        "city": "Pune",
        "state": "Maharashtra",
        "course": "B.Tech in Electronics and Telecommunication Engineering",
        "course_fee": "1550000",
        "average_package": "1500000",
        "highest_package": "4500000",
        "collegeduniya_rating": "8.5",
        "user_rating": "8.3",
        "featured": false
    },
    {
        "ranking": "77",
        "name": "BITS Hyderabad - Birla Institute of Technology and Science, Hyderabad",
        "city": "Hyderabad",
        "state": "Telangana",
        "course": "B.Tech in Chemical Engineering",
        "course_fee": "1450000",
        "average_package": "1400000",
        "highest_package": "4400000",
        "collegeduniya_rating": "8.4",
        "user_rating": "8.2",
        "featured": false
    },
    {
        "ranking": "98",
        "name": "LNM Institute of Information Technology, Jaipur",
        "city": "Jaipur",
        "state": "Rajasthan",
        "course": "B.Tech in Computer Science and Engineering",
        "course_fee": "1600000",
        "average_package": "1700000",
        "highest_package": "4700000",
        "collegeduniya_rating": "8.7",
        "user_rating": "8.5",

        "featured": false
    },
    {
        "ranking": "71",
        "name": "IIIT Hyderabad - International Institute of Information Technology, Hyderabad",
        "city": "Hyderabad",
        "state": "Telangana",
        "course": "B.Tech in Artificial Intelligence",
        "course_fee": "1650000",
        "average_package": "1800000",
        "highest_package": "4800000",
        "collegeduniya_rating": "9.0",
        "user_rating": "8.8",

        "featured": false
    },
    {
        "ranking": "83",
        "name": "SRM University, Chennai",
        "city": "Chennai",
        "state": "Tamil Nadu",
        "course": "B.Tech in Biotechnology",
        "course_fee": "1700000",
        "average_package": "1750000",
        "highest_package": "4800000",
        "collegeduniya_rating": "8.8",
        "user_rating": "8.6",

        "featured": false
    },
    {
        "ranking": "145",
        "name": "KIIT University, Bhubaneswar",
        "city": "Bhubaneswar",
        "state": "Odisha",
        "course": "B.Tech in Computer Engineering",
        "course_fee": "1550000",
        "average_package": "1600000",
        "highest_package": "4700000",
        "collegeduniya_rating": "8.6",
        "user_rating": "8.4",

        "featured": false
    },
    {
        "ranking": "79",
        "name": "Manipal Academy of Higher Education, Manipal",
        "city": "Manipal",
        "state": "Karnataka",
        "course": "B.Tech in Information Technology",
        "course_fee": "1650000",
        "average_package": "1700000",
        "highest_package": "4800000",
        "collegeduniya_rating": "8.9",
        "user_rating": "8.7",

        "featured": false
    },
    {
        "ranking": "78",
        "name": "Christ University, Bangalore",
        "city": "Bangalore",
        "state": "Karnataka",
        "course": "B.Tech in Electronics and Communication Engineering",
        "course_fee": "1600000",
        "average_package": "1650000",
        "highest_package": "4800000",
        "collegeduniya_rating": "8.7",
        "user_rating": "8.5",

        "featured": false
    }
]